version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on: []
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000/api}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
