# Generated by Django 5.0.6 on 2024-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Civil_Engineer', 'Civil Engineer'), ('Traffic_Engineer', 'Traffic Engineer'), ('Civil_or_Mechanical_Engineer', 'Civil or Mechanical Engineer'), ('Environmental_Engineer', 'Environmental Engineer'), ('Electrical_Engineer', 'Electrical Engineer'), ('Public_Relations_Specialist', 'Public_Relations_Specialist'), ('Document_Controller', 'Document_Controller'), ('Stakeholder_Relations_Manager', 'Stakeholder Relations Manager'), ('Project_Manager', 'Project Manager')], max_length=50),
        ),
    ]
