# Generated by Django 5.0.6 on 2024-09-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Traffic Engineer', 'Traffic Engineer'), ('Civil or Mechanical Engineer', 'Civil or Mechanical Engineer'), ('Environmental Engineer', 'Environmental Engineer'), ('Electrical Engineer', 'Electrical Engineer'), ('Public Relations Specialist', 'Public Relations Specialist'), ('Document Controller', 'Document Controller'), ('Stakeholder Relations_Manager', 'Stakeholder Relations Manager'), ('Project Manager', 'Project Manager')], max_length=50),
        ),
    ]
