# Generated by Django 5.0.6 on 2024-11-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Traffic Engineer', 'Traffic Engineer'), ('Civil or Mechanical Engineer', 'Civil or Mechanical Engineer'), ('Environmental Engineer', 'Environmental Engineer'), ('Electrical Engineer', 'Electrical Engineer'), ('Public Relations Officer (PRO)', 'Public Relations Officer (PRO)'), ('Document Controller', 'Document Controller'), ('Project Manager', 'Project Manager'), ('Stakeholder', 'Stakeholder'), ('Draftsman', 'Draftsman'), ('QA-QC Engineer', 'QA-QC Engineer'), ('Site Engineer', 'Site Engineer'), ('Surveyor', 'Surveyor')], max_length=50),
        ),
    ]
