name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.1.3-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Backend check
        run: |
          docker build -f backend/Dockerfile -t rag-backend:ci .
          docker run --rm rag-backend:ci bash -lc "python manage.py check"
      - name: Frontend build
        run: |
          docker build -f frontend/Dockerfile -t rag-frontend:ci .
